apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

# Important: This keeps the name consistent for the HelmRelease to find
generatorOptions:
  disableNameSuffixHash: true

resources:
- helmrelease_podinfo.yaml
- values.yaml
